name: SpawnPlugin
author: TDR_Minecraft
version: tdrstudios.01
main: de.tdrstudios.spawn.SpawnPlugin
commands:
  spawn:
    permission: tdrstudios.spawn
    description: TP to Spawn
    usage: /<command>
  setspawn:
    permission: tdrstudios.setspawn
    usage: /<command>
